dist: trusty

addons:
  chrome: stable

language: python

python:
  - "3.6"

install:
  - pwd
  - echo $DB_INFO > ./natphoto/app/dbinfo.txt
  - echo $DB_INFO > ./backend/dbinfo.txt
  - pip install -r ./natphoto/requirements.txt
  - npm install -g npm
  - cd ./react/natphoto
  - npm install
  - cd ../../
  # nohup npm start &
  # google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000 &

script:
  - make travis
