dist: trusty

addons:
  chrome: stable

language: python

python:
  - "3.6"

install:
  - pwd
  - echo $DB_INFO > ./backend/dbinfo.txt
  - pip install -r requirements.txt
  - npm install -g npm
  - cd ./frontend
  - npm install
  - cd ../

script:
  - make travis
