language: python

python:
  - "3.6"

install:
  - pwd
  - echo $DB_INFO > ./natphoto/app/dbinfo.txt
  - echo $DB_INFO > ./backend/dbinfo.txt
  - pip install -r ./natphoto/requirements.txt

script:
  - make test
