dist: trusty

addons:
  chrome: stable

language: python

python:
  - "3.6"

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - pwd
  - echo $DB_INFO > ./natphoto/app/dbinfo.txt
  - echo $DB_INFO > ./backend/dbinfo.txt
  - pip install -r ./natphoto/requirements.txt
  - npm install -g npm
  - cd ./react/natphoto && npm install
  - cd ../../

script:
  - make test
