FROM tiangolo/uwsgi-nginx-flask:python3.6

RUN pwd

# Copy in the current files
COPY ./requirements.txt /app/requirements.txt

# Install the required files for the app
RUN pip install -r requirements.txt

COPY ./backend /app
