FROM python:3.6.2

# Install any required linux items
RUN apt-get update              && \
    apt-get -y install vim

# Install basic python tools
RUN pip install --upgrade pip       && \
    pip --version                   && \
    pip install autopep8            && \
    pip install coverage            && \
    pip install mypy                && \
    pip install pylint

# Copy in the current files
COPY ./requirements.txt /requirements.txt

# Install the required files for the app
RUN pip install -r requirements.txt

CMD bash
